language: python
python:
  - 3.6
notifications:
  email: false

# Setup anaconda and install packages
# updated based on
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - sudo apt-get update
  # load miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;

  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy astropy pybind11 pytest pandoc
  - conda activate test-environment
  # Use pip to install our rtd required packages
  - pip install -r docs/rtd-pip-requirements
  - python setup.py install

# Run test
script:
  - pytest tests --ignore=tests/test_regressions.py --ignore=tests/test_docs.py --ignore=tests/test_multiresolution.py

# Calculate coverage
#after_success:
#  - coveralls --config_file .coveragerc
